#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /blog
  controller: App\Controller\BlogController::index

new:
  path: /new
  controller: App\Controller\BlogController::new